#!/usr/bin/env bash

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source=$1

echo "{\"version\": {\"time\": \"$(date +%s)\", \"in\": \"$source\"}}" >&3
